// src/pages/Index.vue
<template>
  <Layout>
    <body class="is-preload">
      <!-- Page Wrapper -->
      <div id="page-wrapper">
        <!-- Main -->
        <div id="main">
          <!-- One -->
          <section id="one" class="features">
            <header class="major" id="one-header">
              <h2>Everyone Plays the Same Song</h2>
              <p>A FUN AND EDUCATIONAL COMMUNITY COVERS PROJECT</p>
            </header>
            <div class="content">
              <section class="feature">
                <h3>How it Works</h3>
                All participants
                <ul>
                  <li>Sign up by submitting a song they'd like to cover.</li>
                  <li>
                    Vote on the song they want to cover. The song with the
                    highest average is the song to cover.
                  </li>
                  <li>
                    Record and submit a cover of the song by the submission
                    deadline.
                  </li>
                  <li>
                    Celebrate at a virtual listening party with all other
                    participants.
                  </li>
                </ul>
                <g-link :to="mainPost.path + `#project-details`">
                  <button id="more-info-link">More Info</button>
                </g-link>
              </section>
              <section class="feature">
                <h3>The Numbers</h3>
                So far and counting
                <ul>
                  <li>4 Rounds</li>
                  <li>24 unique participants</li>
                  <li>From 8 different cities</li>
                  <li>In 3 different time zones</li>
                </ul>
              </section>
              <section class="feature">
                <h3>How to Get Involved</h3>
                <p>Round 5 Signups are currently under way!</p>
                <g-link
                  id="signup-link"
                  to="https://forms.gle/Taob3tREZhJQrRHb9"
                >
                  <button style="color: black">Sign Up</button>
                </g-link>
              </section>
            </div>
          </section>
          <div id="rounds">
            <round-display
              v-for="(post, i) in postsWithRoundMetadata"
              :index="i"
              :post="post"
              :key="post.title"
            />
          </div>
          <!-- Five -->
          <section id="get-involved">
            <h2>Want to throw your cover into the ring?</h2>
            <p>
              Participating in Everyone Plays the Same Song is a way to join a
              community of musicians, deliver a project on a deadline and flex
              your skills.
            </p>
            <ul class="actions special">
              <li>
                <g-link
                  id="signup-link"
                  to="https://forms.gle/Taob3tREZhJQrRHb9"
                >
                  <button style="color: black">Sign Up</button>
                </g-link>
              </li>
            </ul>
          </section>
        </div>
      </div>
    </body>
  </Layout>
</template>

<page-query>
query Posts {
  posts: allPost(filter: { published: { eq: true }}) {
    edges {
      node {
        id
        title
        date
        description
        path
        excerpt
        published
        favorite
        tags {
          title
        }
    }
  }
  }
    rounds: allRounds {
    edges {
      node {
        id
        round
        title
        image
        playlist
    }
  }
  }
  }
  </page-query>


<script>
import RoundDisplay from "../components/home/RoundDisplay";

export default {
  metaInfo: {
    title: "Everyone Plays the Same Song",
  },
  data() {
    return {
      mailingList: "https://forms.gle/WWExzdN3e61Ko3J28",
    };
  },
  components: {
    RoundDisplay,
  },
  computed: {
    posts() {
      return this.$page.posts.edges
        .map((edge) => edge.node)
        .filter(
          (post) => !post.tags.map((tag) => tag.title).includes("eptss-main")
        );
    },
    rounds(){
      return this.$page.rounds.edges
        .map((edge) => edge.node)
    },
    postsWithRoundMetadata(){
      return this.posts.map(post => {
        const eptssTag = post.tags.find(tag => tag.title.includes('eptss'));
        const roundNumber = eptssTag.title.slice(-1);
        const roundObj = this.rounds.find(round => round.round == roundNumber);
        post.song = roundObj.title;
        post.playlist = roundObj.playlist;
        post.image = roundObj.image;
        return post;
      })
    },
    mainPost() {
      return this.$page.posts.edges
        .map((edge) => edge.node)
        .find((post) =>
          post.tags.map((tag) => tag.title).includes("eptss-main")
        );
    },
  },
};
</script>

<style>
#one-header {
  background-image: url("../assets/images/section_one_bg.jpg");
  background-size: 100%;
}

#get-involved {
  color: black;
  padding: 2rem;
}

#get-involved h2 {
  color: black;
}

#get-involved button {
  color: black !important;
}
</style>

// src/pages/index.tsx
import React from "react"
import { Link, graphql } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"
import RoundDisplay from "../components/roundDisplay"
import SignupButton from "../components/signupButton"
import getCurrentBlurb from "../hooks/getOverviewBlurb";

type IndexPageProps = {
  data: {
    allMarkdownRemark: {
      edges: [
        {
          node: {
            fields: {
              slug: string,
              playlist: string,
              song: string
            }
            frontmatter: {
              date: string,
              description: string,
              favorite: boolean,
              published: boolean,
              title: string,
            }
          }
        }
      ]
    }
  }
}

const IndexPage: React.FC<IndexPageProps> = ({ data }) => {
  const GENERAL_INFO_SLUG = '/everyone-plays-the-same-song/';

  const nodes = data.allMarkdownRemark.edges.map(edge => edge.node)
  const roundPosts = nodes.filter(node => node.fields.slug !== GENERAL_INFO_SLUG)
  const currentProjectOverviewBlurb = getCurrentBlurb();

  return (
    <Layout>
      <SEO title="Everyone Plays the Same Song" />
      <section className="hero">
        <div className="hero-container">
          <h1>Everyone Plays the Same Song</h1>
          <p>
            Everyone Plays the Same Song is a fun and educational community covers
            project. Members suggest and vote on songs to cover, submit their
            songs and then celebrate with a listening party. Please sign up and
            join us for the next round.
        </p>
          <div className="button-container">
            <Link to={GENERAL_INFO_SLUG}>
              <button>Learn</button>
            </Link>
            <Link to="/#listen">
              <button>Listen</button>
            </Link>
            <SignupButton />
          </div>
        </div>
      </section>

      <main className="main">
        <div className="content-container">
          <div className="card-header">
            <h2>How It Works</h2>
            <hr />
          </div>
          <div className="card">
            <div className="hiw">
              <div className="item-third">
                <h3>1. Sign Up</h3>
                <p>Sign up and submit a song that you would like to cover.</p>
              </div>
              <div className="item-third">
                <h3>2. Select</h3>
                <p>
                  Vote for the song that all participants will cover as a
                  community.
              </p>
              </div>
              <div className="item-third">
                <h3>3. Submit</h3>
                <p>
                  Submit your cover and celebrate with a virtual listening party.
              </p>
              </div>
            </div>
            <p className="hiw">
              {currentProjectOverviewBlurb}
            </p>
            <div className="button-container">
              <Link to={GENERAL_INFO_SLUG} id="learn">
                <button>Learn More</button>
              </Link>
              <button>
                <Link to="#listen">Listen</Link>
              </button>
              <SignupButton />
            </div>
          </div>
          <div className="card-header">
            <h2><a id="listen">Community Covers</a></h2>
            <hr />
          </div>
          {roundPosts.map(node => {
            return (
              <RoundDisplay
                key={node.fields.slug}
                round={node}
              />
            )
          })}
        </div>
      </main>

      <footer className="footer">
        <div className="button-container">
          <SignupButton />
        </div>
      </footer>
    </Layout >
  )
}

export const query = graphql`
  query HomePageQuery {
    allMarkdownRemark(sort: {fields: frontmatter___date, order: DESC}) {
    edges {
      node {
        fields{
          slug
          playlist
          song
        }
        frontmatter {
          date
          description
          favorite
          published
          title
        }
      }
    }
  }
  }
`

export default IndexPage
